# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/monokai-pro.toml"]

[font]
size = 17.0

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0
