# themes from https://github.com/alacritty/alacritty-theme
general.import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]

[font]
size = 26.0

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 0
