#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

yabai -m rule --add app="^Brave$" space=1
yabai -m rule --add app="^Alacritty$" space=2
yabai -m rule --add app="^Google Chrome$" space=3
yabai -m rule --add app="^(TIDAL|Spotify)$" space=4
