#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 5)'); do
  yabai -m space --destroy 6
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 browser
setup_space 2 code
setup_space 3 testing
setup_space 4 music
setup_space 5 other

yabai -m rule --add app="Brave" space=1
yabai -m rule --add app="Alacritty" space=2
yabai -m rule --add app="Google Chrome" space=3
yabai -m rule --add app="(TIDAL|Spotify)" space=4
